import React from 'react'
import { Link } from 'gatsby'
import Helmet from 'react-helmet'
import Layout from '../components/layout'
import VtLanding from '../components/vtLanding'

import pic08 from '../assets/images/pic08.jpg'
import pic09 from '../assets/images/pic09.jpg'
import pic10 from '../assets/images/pic10.jpg'

const ViewThrough = (props) => (
    <Layout>
        <Helmet>
            <title>ViewThrough</title>
            <meta name="description" content="ViewThrough" />
        </Helmet>

        <VtLanding />

        <div id="main">
            <section id="one">
                <div className="inner">
                    <header className="major">
                        <h2>What is ViewThrough?</h2>
                    </header>
                    <p>Similar to a 'view through conversion', where an advertiser wants to attribute a conversion that happens on their website to an ad impression served to a user previously, this new View Through extension allows customers to track user interaction with ads and retrieve that tracking data when the end user later comes to their website. Any data points produced by the customer's adserver (i.e. DCM) can be dynamically populated into the tracking pixel, and later collected when the user hits the website.</p>
                    <ul className="actions">
                        <li><Link to="/demoSteps" className="button">Live Demo</Link></li>
                    </ul>
                </div>
            </section>
            <section id="two" className="spotlights">
                <section>
                    <Link to="/hit1" className="image">
                        <img src={pic08} alt="" />
                    </Link>
                    <div className="content">
                        <div className="inner">
                            <header className="major">
                                <h3>How does it work?</h3>
                            </header>
                            <p>The new View Through extension enables clients to track ad impressions served to their users via a tracking pixel, as well as associated metadata about the impressions generated by the ad server. The tracking pixel collects and stores data in a cookie, and when the user comes back to your website the View Through extension will add the collected data to the data layer for use in other tags or EventStream & AudienceStream.</p>
                            <ul className="actions">
                                <li><Link to="/hit1" className="button">Trigger 1</Link></li>
                            </ul>
                        </div>
                    </div>
                </section>
                <section>
                    <Link to="/hit2" className="image">
                        <img src={pic09} alt="" />
                    </Link>
                    <div className="content">
                        <div className="inner">
                            <header className="major">
                                <h3>Why did we build it?</h3>
                            </header>
                            <p>Advertisers are always looking to gather more data about how their users are interacting with their ads as they browse the internet. Most ad exchanges and networks are very restrictive about what data can be collected and how the advertiser can acquire said data. Once an advertiser does get some of this campaign level data, it's very hard to tie it back to a user/customer profile for a variety of reasons. For some brands, these micro-interactions are valuable milestones that they want to track and have represented in their 360-degree view of their customers.
                            <br></br>
                            Now with Tealium View Through, you can easily track those interactions and immediately get access to the data when a user comes back to your site. With that data in the data layer, clients can create more robust visitor profile attributes, audiences, and activation strategies downstream via the connector marketplace. You may want to keep track of total impressions served to a user, a list of the campaigns they were exposed to, or the specific creatives they've seen. All of these data points can now be used in your broader 1st party data strategy.</p>
                            <ul className="actions">
                                <li><Link to="/hit2" className="button">Trigger 2</Link></li>
                            </ul>
                        </div>
                    </div>
                </section>
                {/* <section>
                    <Link to="/generic" className="image">
                        <img src={pic10} alt="" />
                    </Link>
                    <div className="content">
                        <div className="inner">
                            <header className="major">
                                <h3>Sed nunc ligula</h3>
                            </header>
                            <p>Nullam et orci eu lorem consequat tincidunt vivamus et sagittis magna sed nunc rhoncus condimentum sem. In efficitur ligula tate urna. Maecenas massa sed magna lacinia magna pellentesque lorem ipsum dolor. Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis tempus.</p>
                            <ul className="actions">
                                <li><Link to="/generic" className="button">Learn more</Link></li>
                            </ul>
                        </div>
                    </div>
                </section> */}
            </section>
        </div>

    </Layout>
)

export default ViewThrough